export const searchIndex = [
  // Blog articles
  {
    title: "How to Calculate Mortgage Payments: A Complete Guide",
    description: "Learn the math behind mortgage payments with real examples.",
    url: "/blog/mortgage-payment-guide",
    category: "Mortgage Guides",
  },
  {
    title: "How Much House Can I Afford in 2026?",
    description: "Find out how much house you can afford using the 28/36 rule.",
    url: "/blog/how-much-house-can-i-afford",
    category: "Home Buying",
  },
  {
    title: "Rent vs. Buy in 2026: A Data-Driven Guide",
    description: "Compare the real costs of renting vs buying a home.",
    url: "/blog/rent-vs-buy-2026",
    category: "Home Buying",
  },
  {
    title: "Fixed vs. Variable Mortgage: Which Should You Choose?",
    description: "Compare fixed and adjustable rate mortgages with real numbers.",
    url: "/blog/fixed-vs-variable-mortgage",
    category: "Mortgage Guides",
  },
  {
    title: "When Does Refinancing Make Sense?",
    description: "Calculate your break-even point and decide if refinancing is right.",
    url: "/blog/when-to-refinance",
    category: "Refinancing",
  },
  {
    title: "Down Payment Guide 2026",
    description: "How much down payment do you really need to buy a house?",
    url: "/blog/down-payment-guide",
    category: "Home Buying",
  },
  {
    title: "How to Pay Off Your Mortgage Early",
    description: "Strategies that actually work — with exact interest savings.",
    url: "/blog/early-mortgage-payoff",
    category: "Mortgage Guides",
  },
  {
    title: "How Interest Rates Affect Your Mortgage Payment",
    description: "See the exact dollar impact of every rate change.",
    url: "/blog/interest-rate-impact",
    category: "Mortgage Guides",
  },
  {
    title: "What Is an Amortization Schedule?",
    description: "Learn how to read an amortization schedule with real examples.",
    url: "/blog/amortization-schedule-explained",
    category: "Mortgage Guides",
  },
  {
    title: "How to Use a Loan Calculator",
    description: "A complete guide to loan calculators with real examples.",
    url: "/blog/loan-calculator-explained",
    category: "Loan Guides",
  },
  {
    title: "How to Compare Loan Offers",
    description: "The 6 numbers that actually matter beyond the monthly payment.",
    url: "/blog/compare-loan-offers",
    category: "Loan Guides",
  },
  {
    title: "Loan Eligibility by Income",
    description: "How much can you borrow based on your salary in 2026?",
    url: "/blog/loan-eligibility-by-income",
    category: "Loan Guides",
  },
  {
    title: "Loan Eligibility by Income — Detailed Tables",
    description: "Detailed borrowing limits for every salary level in 2026.",
    url: "/blog/loan-eligibility-by-income-detail",
    category: "Loan Guides",
  },
  {
    title: "The Monthly Payment Formula Explained",
    description: "Calculate any loan payment manually with step-by-step examples.",
    url: "/blog/monthly-payment-formula",
    category: "Loan Guides",
  },
  {
    title: "Total Interest Paid on a Loan",
    description: "What it really costs to borrow — with strategies to reduce it.",
    url: "/blog/total-interest-explained",
    category: "Loan Guides",
  },
  {
    title: "VA Loans Guide 2026",
    description: "Everything veterans need to know about VA loans.",
    url: "/blog/va-loans-guide",
    category: "Mortgage Guides",
  },
  {
    title: "How to Reduce Your Mortgage Payment",
    description: "8 proven strategies to lower your monthly mortgage cost.",
    url: "/blog/reduce-mortgage-payment",
    category: "Mortgage Guides",
  },
  {
    title: "The 2026 Homebuyer's Playbook",
    description: "Step-by-step guide to buying a home smart in 2026.",
    url: "/blog/2026-homebuyers-playbook",
    category: "Home Buying",
  },
  {
    title: "$100,000 Mortgage Monthly Payment",
    description: "Full breakdown for every rate and term on a $100k mortgage.",
    url: "/blog/100k-mortgage-monthly-payment",
    category: "Mortgage Guides",
  },
  {
    title: "$200,000 Mortgage Monthly Payment",
    description: "Full breakdown for every rate and term on a $200k mortgage.",
    url: "/blog/200k-mortgage-monthly-payment",
    category: "Mortgage Guides",
  },
  {
    title: "Closing Costs Explained",
    description: "Every fee you will pay at closing — and how to reduce them.",
    url: "/blog/closing-costs-breakdown",
    category: "Home Buying",
  },
  {
    title: "Escrow Accounts Explained",
    description: "What escrow is, what goes into it, and why your payment changes.",
    url: "/blog/escrow-accounts-explained",
    category: "Mortgage Guides",
  },
  {
    title: "7 Mortgage Calculator Mistakes",
    description: "Common errors that lead to budget surprises — and how to avoid them.",
    url: "/blog/calculator-mistakes",
    category: "Guides",
  },
  {
    title: "Home Purchase Budget: Everything You Need to Save",
    description: "The complete upfront cost picture before buying a home.",
    url: "/blog/home-purchase-budgeting",
    category: "Home Buying",
  },
  {
    title: "How to Use a Refinance Calculator",
    description: "Step-by-step guide to calculating your refinance break-even.",
    url: "/blog/refinance-calculator-guide",
    category: "Refinancing",
  },
  {
    title: "The Impact of Extra Mortgage Payments",
    description: "Exact numbers for every extra payment amount from $50 to $1,000.",
    url: "/blog/extra-payments-impact",
    category: "Mortgage Guides",
  },
  {
    title: "€300,000 Euro Mortgage",
    description: "Monthly payments, rates, and full cost breakdown for European buyers.",
    url: "/blog/300k-euro-mortgage",
    category: "European Guides",
  },
  {
    title: "€200,000 Euro Mortgage",
    description: "Monthly payments and full cost breakdown for European buyers.",
    url: "/blog/200k-euro-mortgage",
    category: "European Guides",
  },
  {
    title: "15-Year vs. 30-Year Mortgage",
    description: "Which term is right for you? Real numbers for every loan amount.",
    url: "/blog/15-vs-30-year-mortgage",
    category: "Mortgage Guides",
  },
  {
    title: "The 28/36 Rule Explained",
    description: "How lenders use this ratio to determine how much you can borrow.",
    url: "/blog/28-36-rule-explained",
    category: "Guides",
  },
  // Calculator pages
  {
    title: "Mortgage Calculator",
    description: "Calculate your monthly mortgage payment including taxes and insurance.",
    url: "/mortgage-calculator",
    category: "Calculators",
  },
  {
    title: "Loan Calculator",
    description: "Calculate monthly payments and total interest for any loan.",
    url: "/loan-calculator",
    category: "Calculators",
  },
  {
    title: "Affordability Calculator",
    description: "Find out how much house you can afford based on your income.",
    url: "/affordability-calculator",
    category: "Calculators",
  },
  {
    title: "Amortization Schedule",
    description: "Generate a full month-by-month loan repayment schedule.",
    url: "/amortization-schedule",
    category: "Calculators",
  },
  {
    title: "Refinancing Calculator",
    description: "Calculate your refinance savings and break-even point.",
    url: "/refinancing-calculator",
    category: "Calculators",
  },
  {
    title: "Rent vs. Buy Calculator",
    description: "Compare the true cost of renting vs. buying in your market.",
    url: "/rent-vs-buy",
    category: "Calculators",
  },
  {
    title: "Monthly Payment Calculator",
    description: "Calculate the monthly payment on any loan instantly.",
    url: "/monthly-payment-calculator",
    category: "Calculators",
  },
  {
    title: "Total Interest Calculator",
    description: "See the full interest cost of any loan over its lifetime.",
    url: "/total-interest-calculator",
    category: "Calculators",
  },
];
