import Link from 'next/link';
import { MainLayout } from '@/components/layout/MainLayout';
import { SEOHandler } from '@/components/seo/SEOHandler';
import { FUNDING } from '@/lib/trust';
export default function EditorialPolicy() {
 return <MainLayout><SEOHandler title="Editorial Policy and Corrections" description="Authorship, source selection, substantive updates, funding disclosures and error correction at TryFinCalc." canonicalUrl="https://tryfincalc.com/editorial-policy"/>
 <article className="max-w-3xl mx-auto px-6 py-16 space-y-6"><h1 className="text-4xl font-bold text-primary">Editorial policy and corrections</h1>
 <p>Policy updated September 20, 2026. Maintainer: <Link href="/about" className="underline">Youssef Aaouam</Link>.</p>
 <h2 className="text-2xl font-bold">Authorship and human review</h2><p>Youssef Aaouam creates and maintains the calculators and educational guides. The site does not claim a team of financial professionals or external expert review. Author attribution is not a claim of licensed financial, tax or legal expertise. A human publication review must confirm intent, calculations, sources and assumptions before a scenario is marked reviewed. Automated checks do not substitute for that review; no reviewer name is added without that person completing the work.</p>
 <h2 className="text-2xl font-bold">Sources and financial examples</h2><p>Use original regulator, government, lender disclosure or academic sources for material claims. Identify the relevant jurisdiction and effective date for rules, rates and programs. A link to a regulator homepage does not support a specific numerical claim. Examples use the <Link href="/methodology" className="underline">shared calculation methodology</Link>; assumed rates are labeled as scenarios and are not current offers.</p>
 <h2 className="text-2xl font-bold">Substantive updates</h2><p>Change a substantive update date when calculations, assumptions, sourced claims or analysis change materially. A rebuild, cosmetic edit or new calendar year does not justify a new content date. Preserve original publication dates when known; do not invent missing dates. Review overlapping guides for consolidation instead of adding amount/rate permutations.</p>
 <h2 className="text-2xl font-bold">Conflicts and funding</h2><p>{FUNDING}</p><p>Disclose any affiliate relationship next to the relevant link before readers act. Separate advertisements from calculation results. No paid endorsement, traffic count or user review is asserted without evidence.</p>
 <h2 className="text-2xl font-bold">Correction handling</h2><p>Email <a href="mailto:hello@tryfincalc.com" className="underline">hello@tryfincalc.com</a> with the URL, calculation inputs, expected output and a supporting source if available. Do not include account numbers or sensitive personal information. The maintainer should reproduce reported errors, add a regression check where applicable, correct all affected examples, and record material formula changes in the methodology version history. Materially unreliable pages should be held from indexing until corrected.</p>
 <p>Educational estimates cannot replace personalized advice or a lender&apos;s offer. See the <Link href="/terms-of-service" className="underline">Terms</Link> and <Link href="/privacy-policy" className="underline">Privacy Policy</Link>.</p></article></MainLayout>;
}
