import React from 'react';
import Link from 'next/link';
import { MainLayout } from '@/components/layout/MainLayout';
import { SEOHandler } from '@/components/seo/SEOHandler';
import { IncomeNeededCalculator, INCOME_NEEDED_DEFAULTS } from '@/components/calculator/IncomeNeededCalculator';
import { calculateIncomeRequired, formatCurrency } from '@/lib/finance';
import { generateBreadcrumbSchema, generateFAQSchema, generateWebApplicationSchema } from '@/lib/schema';

const DESCRIPTION = 'Estimate annual income for a target home price using adjustable debt, down payment, interest rate, term, property tax and insurance assumptions.';

const initialResult = calculateIncomeRequired(
  INCOME_NEEDED_DEFAULTS.homePrice,
  INCOME_NEEDED_DEFAULTS.monthlyDebts,
  INCOME_NEEDED_DEFAULTS.downPayment,
  INCOME_NEEDED_DEFAULTS.interestRate,
  INCOME_NEEDED_DEFAULTS.loanTerm,
  INCOME_NEEDED_DEFAULTS.monthlyPropertyTax,
  INCOME_NEEDED_DEFAULTS.monthlyInsurance,
);

const tableScenarios = [
  { label: '20% down; no other debt', downPercent: 20, monthlyDebts: 0 },
  { label: '10% down; no other debt', downPercent: 10, monthlyDebts: 0 },
  { label: '20% down; $1,200 monthly debt', downPercent: 20, monthlyDebts: 1200 },
] as const;

const homePriceRows = [200000, 300000, 400000, 500000, 600000, 700000].map((homePrice) => ({
  homePrice,
  results: tableScenarios.map((scenario) => calculateIncomeRequired(
    homePrice,
    scenario.monthlyDebts,
    homePrice * scenario.downPercent / 100,
    6.5,
    30,
    homePrice * 0.01 / 12,
    homePrice * 0.0035 / 12,
  )),
}));

const faqs = [
  {
    question: 'Is the displayed income a lender approval requirement?',
    answer: 'No. It is a planning estimate produced from the displayed ratios and adjustable mathematical assumptions. It does not represent a lender decision or approval guarantee.',
  },
  {
    question: 'What costs are included?',
    answer: 'The calculator includes principal, interest, entered monthly property tax, and entered monthly property insurance. Other costs remain excluded unless represented in those inputs.',
  },
  {
    question: 'Why can monthly debt increase the estimated income?',
    answer: 'The selected total-debt planning ratio compares housing cost plus entered monthly debts with gross income. When that constraint becomes tighter than the housing-only ratio, more income is required in the model.',
  },
];

const schemas = [
  generateWebApplicationSchema({
    name: 'Income Needed for a House Calculator',
    path: '/income-needed-for-a-house',
    description: DESCRIPTION,
  }),
  generateBreadcrumbSchema([
    { name: 'Home', item: 'https://tryfincalc.com' },
    { name: 'Income Needed for a House', item: 'https://tryfincalc.com/income-needed-for-a-house' },
  ]),
  generateFAQSchema(faqs),
];

export default function IncomeNeededForAHousePage() {
  return (
    <MainLayout>
      <SEOHandler
        title="Income Needed for a House Calculator"
        description={DESCRIPTION}
        canonicalUrl="https://tryfincalc.com/income-needed-for-a-house"
        structuredData={schemas}
      />

      <header className="mx-auto max-w-7xl px-4 pb-8 pt-16 sm:px-6 lg:px-8 lg:pt-24">
        <div className="max-w-4xl">
          <p className="mb-4 text-xs font-bold uppercase tracking-[0.2em] text-primary">Income planning scenario</p>
          <h1 className="mb-6 font-display text-4xl font-extrabold leading-tight text-primary md:text-6xl">
            How Much Income Is Needed for a House?
          </h1>
          <p className="max-w-3xl text-xl leading-relaxed text-on-surface-variant">
            Under the selected $400,000 price, $80,000 down payment, 6.5% annual rate, 30-year term, $500 monthly debt, $400 tax, and $150 insurance assumptions, the illustrative annual gross income is <strong className="text-primary">{formatCurrency(initialResult.requiredAnnualIncome, 0)}</strong>.
          </p>
        </div>
      </header>

      <IncomeNeededCalculator />

      <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8">
        <div className="mb-8 max-w-4xl">
          <h2 className="mb-4 font-display text-3xl font-bold text-primary md:text-4xl">Income estimates from $200,000 to $700,000</h2>
          <p className="text-lg leading-relaxed text-on-surface-variant">
            Every value below is generated by the shared loan and income-planning functions. All three columns use a selected 6.5% nominal annual rate and 30-year term. The property-tax input equals 1% of the displayed price per year and the insurance input equals 0.35% per year; these are transparent mathematical assumptions, not market averages or lender criteria.
          </p>
        </div>
        <div className="overflow-x-auto rounded-3xl border border-outline-variant/30 bg-surface-container-lowest">
          <table className="w-full min-w-[760px] text-left">
            <caption className="p-5 text-left text-sm text-on-surface-variant">Selected planning assumptions only; figures are not an approval guarantee.</caption>
            <thead className="bg-surface-container-high">
              <tr>
                <th className="px-5 py-4 text-sm font-bold text-primary">Home price</th>
                {tableScenarios.map((scenario) => <th key={scenario.label} className="px-5 py-4 text-sm font-bold text-primary">{scenario.label}</th>)}
              </tr>
            </thead>
            <tbody className="divide-y divide-outline-variant/20">
              {homePriceRows.map((row) => (
                <tr key={row.homePrice}>
                  <th className="px-5 py-4 font-bold text-on-surface">{formatCurrency(row.homePrice, 0)}</th>
                  {row.results.map((result, index) => (
                    <td key={tableScenarios[index].label} className="px-5 py-4 tabular-nums text-on-surface-variant">
                      {formatCurrency(result.requiredAnnualIncome, 0)}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="mx-auto grid max-w-7xl gap-8 px-4 pb-20 sm:px-6 lg:grid-cols-2 lg:px-8">
        <div className="rounded-3xl border border-primary/10 bg-primary/5 p-8">
          <h2 className="mb-4 font-display text-2xl font-bold text-primary">What the estimate includes</h2>
          <p className="leading-relaxed text-on-surface-variant">It includes the calculated loan principal and interest plus the entered property tax and insurance. The selected 28% housing and 36% total-debt ratios are labeled planning assumptions.</p>
        </div>
        <div className="rounded-3xl border border-outline-variant/20 bg-surface-container-low p-8">
          <h2 className="mb-4 font-display text-2xl font-bold text-primary">What remains outside the model</h2>
          <p className="leading-relaxed text-on-surface-variant">Maintenance, association dues, closing costs, loan-specific insurance, utilities, tax effects, product fees, and underwriting decisions are excluded. The output is not a guarantee of approval.</p>
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-4 pb-20 sm:px-6 lg:px-8">
        <h2 className="mb-6 font-display text-3xl font-bold text-primary">Continue with the relevant tools and guides</h2>
        <div className="grid gap-4 md:grid-cols-2">
          <Link className="rounded-2xl border border-outline-variant/20 bg-surface-container-low p-5 font-semibold text-primary hover:border-primary" href="/affordability-calculator">Open the Affordability Calculator</Link>
          <Link className="rounded-2xl border border-outline-variant/20 bg-surface-container-low p-5 font-semibold text-primary hover:border-primary" href="/blog/28-36-rule-explained">Understand the selected 28/36 planning ratios</Link>
          <Link className="rounded-2xl border border-outline-variant/20 bg-surface-container-low p-5 font-semibold text-primary hover:border-primary" href="/blog/down-payment-guide">Review down-payment considerations</Link>
          <Link className="rounded-2xl border border-outline-variant/20 bg-surface-container-low p-5 font-semibold text-primary hover:border-primary" href="/blog/home-purchase-budgeting">Build a broader home-purchase budget</Link>
        </div>
      </section>

      <section className="mx-auto max-w-7xl px-4 pb-24 sm:px-6 lg:px-8">
        <h2 className="mb-8 font-display text-3xl font-bold text-primary">Frequently asked questions</h2>
        <div className="grid gap-8 md:grid-cols-3">
          {faqs.map((faq) => (
            <article key={faq.question} className="rounded-2xl border border-outline-variant/20 p-6">
              <h3 className="mb-3 font-bold text-primary">{faq.question}</h3>
              <p className="text-sm leading-relaxed text-on-surface-variant">{faq.answer}</p>
            </article>
          ))}
        </div>
      </section>
    </MainLayout>
  );
}
