import Link from 'next/link';
import { MainLayout } from '@/components/layout/MainLayout';
import { SEOHandler } from '@/components/seo/SEOHandler';
import { calculateLoan, formatCurrency } from '@/lib/finance';
import { ACCURACY, ASSUMPTIONS_VERSION } from '@/lib/trust';
export default function Methodology() {
  return <MainLayout><SEOHandler title="Calculation Methodology and Assumptions" description="Payment formulas, rounding, financial model assumptions, exclusions and tested examples for TryFinCalc calculators." canonicalUrl="https://tryfincalc.com/methodology"/>
    <article className="max-w-4xl mx-auto px-6 py-16 space-y-6 text-on-surface">
      <h1 className="text-4xl font-bold text-primary">Calculation methodology</h1>
      <p>By <Link href="/about" className="underline">Youssef Aaouam</Link>. Assumptions version {ASSUMPTIONS_VERSION}; substantive update: September 20, 2026.</p><p>{ACCURACY}</p>
      <h2 className="text-2xl font-bold">Fixed-rate payments</h2>
      <p>For principal P, nominal annual percentage rate a, and n monthly payments: r = a / 1200; M = P × r / (1 − (1 + r)<sup>−n</sup>). At zero interest, M = P / n. Payments occur at the end of each month; the rate remains fixed. This follows by summing the present values of the n payments: P = Σ M / (1+r)<sup>t</sup>.</p>
      <p>The interest input is a nominal annual interest rate, not a fee-inclusive APR or an effective annual rate. APR can include charges beyond interest: <a className="underline" href="https://www.consumerfinance.gov/ask-cfpb/what-is-the-difference-between-a-mortgage-interest-rate-and-an-apr-en-135/">CFPB explanation of interest rate and APR</a> (accessed September 20, 2026). No rate on this site is a lender quote unless explicitly identified and dated.</p>
      <h2 className="text-2xl font-bold">Units, validation and rounding</h2><p>Money inputs use the displayed currency; rates use percentage points (6 means 6%); terms use years converted to whole months. Loan terms must be 1–1,200 months, principal 0–1 trillion, and rates 0–100%. Empty, negative or nonfinite loan inputs do not produce a displayed result. Rent/buy growth inputs may be negative within the shown model bounds.</p><p>Calculations retain floating-point precision and currency values are rounded only for display, normally to two decimals. Interest equals full-precision total payments minus principal. Adding individually rounded rows may differ by cents. Real lenders can round each payment and adjust the final one; daily accrual, irregular dates and prepayments are not modeled.</p>
      <h2 className="text-2xl font-bold">Amortization and total interest</h2><p>Each month, interest is the opening balance times r; principal is M minus interest. The final row pays the remaining balance. Total interest sums the monthly interest. The loan, monthly-payment, total-interest and amortization tools share this calculation.</p>
      <h2 className="text-2xl font-bold">Inclusions and omissions by tool</h2>
      <ul className="list-disc pl-6 space-y-3"><li>Mortgage: principal and interest plus entered annual property tax and insurance divided by 12, and monthly HOA. PMI, maintenance and closing costs are excluded.</li><li>Loan, monthly payment, total interest and amortization: principal and interest only. Origination fees, insurance, taxes and early repayment charges are excluded.</li><li>Affordability: an illustrative US gross-income housing budget of min(28% × income, 36% × income − other debts), floored at zero. The payment formula is inverted to estimate principal, then down payment is added. Tax, insurance, HOA and PMI are excluded in this tool, so the price is a ceiling under simplified assumptions. Currency does not alter the rule. <a className="underline" href="https://www.consumerfinance.gov/ask-cfpb/what-is-a-debt-to-income-ratio-en-1791/">Lender and loan DTI limits differ</a> (CFPB, accessed September 20, 2026); these budgets are not approval predictions.</li><li>Refinance: compare the remaining balance amortized over the remaining term with the same balance over the new term. Costs are paid upfront. Lifetime difference equals remaining scheduled payments minus new scheduled payments and closing costs. Simple fee recovery divides closing costs by positive monthly savings and is shown only within both terms. This is not an equity-adjusted or discounted break-even. A longer new term can reduce payments and increase total cost.</li><li>Rent vs buy: discount each alternative&apos;s end-of-month cash costs by the assumed after-tax annual investment return, converted with (1 + return)<sup>month/12</sup>. Buying includes down payment and purchase costs at time zero, mortgage payments, tax, maintenance and insurance, less net sale equity at the horizon. Selling costs apply to the assumed future value. Rent rises annually; tax and maintenance follow annually adjusted home value; insurance stays constant. PMI, HOA, tax benefits, capital-gains tax, rent deposits and moving costs are excluded. Negative net ownership cost can reflect assumed gains exceeding costs, not guaranteed profit.</li></ul>
      <h2 className="text-2xl font-bold">Rent/buy sensitivity and break-even</h2><p>Three scenarios move appreciation and investment return in opposite directions by one percentage point. Each is checked annually plus the chosen final horizon. The range covers first sampled crossings only; a scenario may never cross, and a crossing may later reverse. This is not a confidence interval or a recommendation. Property values, rent and investment returns are uncertain.</p>
      <h2 className="text-2xl font-bold">Reference examples and automated checks</h2><p>These fixed-rate 30-year examples are generated from the shared implementation and compared in tests with independently calculated expected values supplied for this audit. All amounts exclude fees, tax and insurance.</p>
      <div className="overflow-x-auto"><table className="w-full text-left"><thead><tr><th>Principal / rate</th><th>Monthly estimate</th><th>Total interest</th></tr></thead><tbody>{[[80000,6],[400000,6.5],[315000,6.8]].map(([p,r])=>{const v=calculateLoan(p,r,30);return <tr key={p}><td className="py-3">{formatCurrency(p,0)} / {r}%</td><td>{formatCurrency(v.monthly,2)}</td><td>{formatCurrency(v.totalInterest,2)}</td></tr>})}</tbody></table></div>
      <p>Tests also cover zero rates, invalid terms and amounts, large values, display rounding, schedule reconciliation, affordability inversion, refinance costs, rent growth, sale equity and opportunity cost. Automated tests are not professional certification or a guarantee.</p>
      <h2 className="text-2xl font-bold">Source hierarchy and versions</h2><p>Formulas are derived above; primary consumer-finance sources explain terminology and omissions, not an endorsement of this site. <a className="underline" href="https://www.consumerfinance.gov/ask-cfpb/what-costs-come-with-taking-out-a-mortgage-en-153/">CFPB mortgage cost guidance</a> describes costs beyond the interest payment (accessed September 20, 2026). Country-specific law requires a dated primary source before publication.</p><p>Version {ASSUMPTIONS_VERSION}: synchronous initial estimates, unified loan totals, explicit US affordability assumptions, refinance fee-recovery limits, removal of hidden PMI and discounted rent/buy sensitivity. This log records substantive changes, not deploy dates.</p>
      <p>Send corrections with URL, inputs and expected result to <a href="mailto:hello@tryfincalc.com" className="underline">hello@tryfincalc.com</a>. See <Link href="/editorial-policy" className="underline">editorial and corrections policy</Link>.</p>
    </article></MainLayout>;
}
